pipeline {
    agent any
    tools {
        maven "M3"
        jdk "JDK11"
    }
    stages {
      stage('Git fetch') {
        steps {
          echo 'Git fetch'
          git url: 'https://github.com/llllsssswwww/spring-petclinic.git/',
              branch: 'main', credentialsId: 'gitCredential'
      }
    }
      stage('Maven Build') {
        steps {
          echo 'Maven Build'
          sh   'mvn -Dmaven.tets.failure.ignore=true clean package'
      }
    }
      stage('Docker Image') {
        steps {
          echo 'Docker Image'
      }
    }
      stage('Image Push') {
        steps {
          echo 'Image Push'
      }
    }
      stage('Codedeploy') {
        steps {
          echo 'Codedeploy'
      }
    }         
  }
}
