pipeline {
    agent any
  
    stages {
      stage('Git fatch') {
        steps {
          echo 'Git fatch'
          git url: 'https://github.com/llllsssswwww/spring-petclinic.git/',
              branch: 'main', credentialsId: 'gitCredential'
      }
    }
      stage('Maven Build') {
        steps {
          echo 'Maven Build'
      }
    }
      stage('Docker Image') {
        steps {
          echo 'Docker Image'
      }
    }
      stage('Image Push') {
        steps {
          echo 'Image Push'
      }
    }
      stage('Codedeploy') {
        steps {
          echo 'Codedeploy'
      }
    }         
  }
}
